# Generated by Django 5.0.14 on 2026-07-20 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('grade', models.CharField(default='8', max_length=20)),
                ('student_class', models.CharField(db_column='class', default='A', max_length=20)),
                ('school', models.CharField(blank=True, default='Vridhi Demo School', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('homework_help', 'Homework Help'), ('reading_together', 'Reading Together'), ('screen_time_limit', 'Screen Time Limit'), ('parent_teacher_chat', 'Parent-Teacher Chat'), ('outdoor_play', 'Outdoor Play'), ('praise_encouragement', 'Praise & Encouragement'), ('routine_check_in', 'Routine Check-in')], max_length=50)),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(default=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_activities', to='dashboard.student')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('English', 'English'), ('Social Studies', 'Social Studies')], default='Math', max_length=50)),
                ('score', models.FloatField(help_text='Score out of 100')),
                ('max_score', models.FloatField(default=100)),
                ('date', models.DateField()),
                ('term_label', models.CharField(blank=True, default='', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='dashboard.student')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WellbeingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood_score', models.FloatField(help_text='0-10 wellbeing index')),
                ('mood_label', models.CharField(choices=[('thriving', 'Thriving'), ('stable', 'Stable'), ('stressed', 'Stressed'), ('struggling', 'Struggling')], default='stable', max_length=20)),
                ('sleep_hours', models.FloatField(default=7.5)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing_logs', to='dashboard.student')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
